# Generated by Django 3.0.4 on 2021-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210617_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=128, unique=True, verbose_name='E-mail'),
        ),
    ]
