# Generated by Django 3.0.4 on 2021-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210617_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Телефон'),
        ),
    ]
