# Generated by Django 3.0.4 on 2021-06-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210617_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('did', 'sid')},
        ),
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('gid', 'date')},
        ),
    ]
