# Generated by Django 3.0.4 on 2021-06-17 17:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210617_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=32, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Введите корректный номер, например: +7 999 123-45-67', 'reqiered': 'Это поле обязательно!'}, max_length=128, region='RU', unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.EmailField(max_length=64, unique=True, verbose_name='Email'),
        ),
    ]
